<a href="https://colab.research.google.com/github/terrysu64/Machine-Learning-and-Data-Science-Projects/blob/main/tf_fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamentals


### Intro to tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [ ]:
vector = tf.constant([10,10])
vector, vector.ndim #vector dimensions

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [ ]:
#creating tensors with tf.variable
var_tensor = tf.Variable([10,7]) #mutable
const_tensor = tf.constant([11,11])
var_tensor,const_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([11, 11], dtype=int32)>)

In [ ]:
var_tensor[1].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  3], dtype=int32)>

In [ ]:
#create random tensors (arbitrary size and numbers)
#could be normal distribution or uniform distribution
tf.random.set_seed(42)
rand_tensor0 = tf.random.Generator.from_seed(42).normal(shape=(3,2))
rand_tensor0

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
#shuffle order of elements in tensor
const_tensor = tf.constant([1,2,3,4])
tf.random.shuffle(const_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 1, 2, 3], dtype=int32)>

### Alternative ways to make tensors

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#numpy
import numpy as np
arr = np.arange(1,25)
tf.constant(arr)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
tf.constant(arr,shape=(6,4))

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

### Getting information from tensors

In [ ]:
#shape, rank, axis, size
tensor = tf.zeros(shape=[2,3,4])

In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 3, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

### Indexing tensors

In [ ]:
tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
tensor[:2,:,:2]

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

In [ ]:
rank2 = tf.constant([[1,1],[1,1]])
rank2.shape

TensorShape([2, 2])

In [ ]:
#add extra dimention
rank3 = rank2[..., tf.newaxis] #wrap individual indices
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [1]],

       [[1],
        [1]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2, axis=0) #i.e wrap which axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]]], dtype=int32)>

### Tensor operations

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tensor+=10 #any basic arithmetic works
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]],

       [[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]]], dtype=float32)>

In [ ]:
#matrix multiplication/dot product
tf.matmul(rank2,rank2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
rank2 @ rank2 #when dims dont match use transpose() over reshape()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

###Changing datatypes of tensors

In [ ]:
tensor = tf.constant([2.2,3.5])
tensor.dtype

tf.float32

In [ ]:
tf.cast(tensor,dtype=tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.2, 3.5], dtype=float16)>

### Aggregating tensors

In [ ]:
tensor = tf.constant([[1,-3],[44,2]])
tf.abs(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  3],
       [44,  2]], dtype=int32)>

In [ ]:
tf.reduce_min(tensor),tf.reduce_max(tensor),tf.reduce_mean(tensor),tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=-3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=44>,
 <tf.Tensor: shape=(), dtype=int32, numpy=11>,
 <tf.Tensor: shape=(), dtype=int32, numpy=44>)

### Position max/min

In [ ]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(tensor), tensor[tf.argmax(tensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
tf.argmin(tensor), tensor[tf.argmin(tensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

###Squeezing tensors

In [ ]:
tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
          0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
          0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
          0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
          0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
          0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
          0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
          0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(tensor) #remove dimensions of 1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

### one-hot encoding tensors

In [ ]:
tensor = [1,2,3,4]
tf.one_hot(tensor, depth=4, on_value=1, off_value=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]], dtype=int32)>

### tensors and numpy

In [ ]:
tensor = tf.constant(np.array([3,3,4]))
np.array(tensor), type(np.array(tensor))

(array([3, 3, 4]), numpy.ndarray)

### Finding access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jul 18 16:12:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    28W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------